name: imersao-workflow-ci-cd

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4.1.1
      - name: Login to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and Push the image to Docker Hub
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./kube-news/src
          file: ./kube-news/src/Dockerfile
          push: true
          tags: |
            franciscoangelo/kube-news:v${{ github.run_number }}
            franciscoangelo/kube-news:latest
          
  Continuous-Deployment:
    runs-on: ubuntu-latest
    needs: ["Continuous-Integration"]
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4.1.1
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Configure the Kubeconfig
        run: aws eks update-kubeconfig --name kubenews-cluster --region us-east-1
      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v4.9
        with:
          manifests: ./kube-news/k8s/deployment.yaml
          images: franciscoangelo/kube-news:v${{ github.run_number }}
